# Generated by Django 3.2.6 on 2021-08-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='gameapp_blog',
        ),
    ]
